version: "3.8"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - "/home/ec2-user/EAPP/CI_CD_Pipeline_main:/usr/local/apache2/htdocs/"
      - "logvolume01:/var/log"
volumes:
  logvolume01: {}